apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: default
type: Opaque
data:
  host: MTkyLjE2OC4xMDAuMTc=  # 192.168.100.17 em base64
  port: NTQzMg==              # 5432 em base64
  database: Y29uc3VtZXI=      # consumer em base64
  username: ZWFzeXByb2ZpbmQ=  # easyprofind em base64
  password: TWFzdGVyQDEyMw==  # Master@123 em base64
  connection-string: SG9zdD0xOTIuMTY4LjEwMC4xNztQb3J0PTU0MzI7RGF0YWJhc2U9Y29uc3VtZXI7VXNlcm5hbWU9ZWFzeXByb2ZpbmQ7UGFzc3dvcmQ9TWFzdGVyQDEyMw==  # Host=192.168.100.17;Port=5432;Database=consumer;Username=easyprofind;Password=Master@123 em base64 